openapi: 3.0.0
info:
  title: Incident Analyzer API
  version: 1.0.0
  description: |
    Riceve un incidente in formato testuale da Security Copilot e restituisce un report generato.

servers:
  - url: https://security-copilot-api.azurewebsites.net

paths:
  /analyze-incident:
    post:
      operationId: AnalyzeIncident
      summary: Analizza un incidente di sicurezza inviato da Copilot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                incident:
                  type: string
                  description: Testo strutturato contenente i dati dell'incidente
              required:
                - incident
      responses:
        '200':
          description: Report generato dall'incidente
          content:
            application/json:
              schema:
                type: object
                properties:
                  report:
                    type: string

