openapi: 3.0.0
info:
  title: Text Analysis API
  version: 1.0.0
paths:
  /analyze-text:
    post:
      summary: Analizza un testo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
      responses:
        '200':
          description: Risposta con analisi del testo
          content:
            application/json:
              schema:
                type: object
                properties:
                  original_text:
                    type: string
                  word_count:
                    type: integer
                  uppercase_version:
                    type: string
                  security_analysis:
                    type: string
